server:
  port: ${PORT:8080}

spring:
  application:
    name: sistema-de-cursos
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-cursos:3306/plataforma_cursos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:yuseth}
    password: ${SPRING_DATASOURCE_PASSWORD:Estefano12}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200,https://frond-cursos-production.up.railway.app}
